### ISSUE TITLE
Include username and password in the steps

### ISSUE THREAD

**Issue by viniciusfcf** [RedHatQuickCourses/rhods-deploy#16]
Consider to include username "minio" and password "minio123" in the "upload" steps

https://redhatquickcourses.github.io/rhods-deploy/rhods-deploy/1.33/chapter1/section2.html#_create_a_data_connection

**Comment by rsriniva** [comment]
@viniciusfcf - the username and password are provided in the IMPORTANT card below the figure? Do you mean to say you need this credentials to log in to minio web console for uploading the model file?

**Comment by viniciusfcf** [comment]
The important card it's after the step to upload. And to upload I need to login in minio server using username and password.
I know that both are the same information, but it's not clear to the user how upload the file to minio. 

<img width="1076" alt="image" src="https://github.com/RedHatQuickCourses/rhods-deploy/assets/14058396/786eb60f-1768-4ea4-9737-0bc225223bb2">

**Comment by rsriniva** [comment]
PR for fix https://github.com/RedHatQuickCourses/rhods-deploy/pull/20

@jramcast - need a +1

@viniciusfcf - please confirm I have added username and password to correct step

**Comment by viniciusfcf** [comment]
LGTM @rsriniva
