### ISSUE TITLE
Creating a Custom Model Serving Runtime

### ISSUE THREAD

**Issue by viniciusfcf** [RedHatQuickCourses/rhods-deploy#17]
Before click the Add button, We should choose one of "Select the model serving platforms this runtime supports" options.

**Comment by viniciusfcf** [comment]
probably it's multi model, single model did not worked

**Comment by rsriniva** [comment]
@jramcast - can you confirm this?

**Comment by jramcast** [comment]
This is a new feature introduced in RHOAI 2.5 https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_self-managed/2.5/html/release_notes/new-features-and-enhancements_relnotes

This course is based on (mostly) version 2.1 iirc, so it does not include the latest features.

**Comment by viniciusfcf** [comment]
Got it, so we could update the RHOAI installation step to make sure we're installing the correct version: https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter1/rhods-install-web-console . html#_demo_installation_of_redhat_openshift_ai

![image](https://github.com/RedHatQuickCourses/rhods-deploy/assets/14058396/b42bdfee-f804-4df5-be12-2be05be1bfb7)
![image](https://github.com/RedHatQuickCourses/rhods-deploy/assets/14058396/9a7e6a6d-cf79-4a5d-b3b0-be7fab9c7966)

**Comment by rsriniva** [comment]
opened issue https://github.com/RedHatQuickCourses/rhods-admin/issues/37 for recommending v2.4 of the RHOAI operator

@jramcast - can you review my issue and add your comments - what do we do with this PR? is there any changes to text in this course?

**Comment by rsriniva** [comment]
@jramcast - can we close this issue and track the other one in the admin course? any text changes to this course?

**Comment by jramcast** [comment]
Yes, I'm closing this issue. Let's track everything in the other one. We might need to add  the `2.4` version id to the home page of every course to make it clear that these courses target RHOAI 2.4, but like I said, let's track those changes in https://github.com/RedHatQuickCourses/rhods-admin/issues/37.
