### ISSUE TITLE
Update podman build instructions to account for Apple ARM64 machines

### ISSUE THREAD

**Issue by cbowland** [RedHatQuickCourses/rhods-deploy#21]
Update instructions in https://redhatquickcourses.github.io/rhods-deploy/rhods-deploy/1.33/chapter1/section1.html to help those using Apple Arm64 architectures to build containers that will run on OpenShift.

Maybe add a quick note that says use

**podman build -t purchase-predictor:1.0 .**

OR when running on an Apple ARM64 machine, use

**podman build --platform linux/amd64 -t purchase-predictor:1.0 .**

The rest of the instructions can remain the same.

**Comment by rsriniva** [comment]
fixed in main. Thanks for the tip @cbowland
