### ISSUE TITLE
Set Route Name In Variable To Be Used In Later Instructions

### ISSUE THREAD

**Issue by cbowland** [RedHatQuickCourses/rhods-deploy#22]
In https://redhatquickcourses.github.io/rhods-deploy/rhods-deploy/1.33/chapter1/section1.html,

The current instructions assume the cluster name and thus the route give is likely incorrect. It might be better to use the oc command to get the route name and then set it in an environment variable to be used in the subsequent steps.

For example:

ROUTE_NAME=$(oc get route purchase-predictor -o jsonpath='{.spec.host}')

Then update the instructions like so

 curl http://$ROUTE_NAME/health
ok

 curl http://$ROUTE_NAME/info
{"name":"Time to purchase amount predictor","version":"v1.0.0"}

 curl -d '{"time":4}' -H "Content-Type: application/json"  -X POST \
 http://ROUTE_NAME/predict
{"prediction":34,"status":200}

**Comment by rsriniva** [comment]
fixed in main. Thanks for the tip @cbowland
