### ISSUE TITLE
Typo user-purchase-amount

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-deploy#25]
Page https://redhatquickcourses.github.io/rhods-deploy/rhods-deploy/1.33/chapter1/section1.html#_use_the_model_in_another_notebook says

> You are not training the model in the **user-purchase-amount** notebook, you are re-using the output from the training notebook, and using the generated model to generate an inference.

The name of the notebook is use-purchase-amount, not user-purchase-amount.

**Comment by rsriniva** [comment]
fixed in main. Thank you @adelton
